<a name="footer-aboutus"></a>
<footer class="footer">
  <div class="group-1">
    <div class="box">
      <figure>
        <a href="#">
          <img src="img/logo.jpg" alt="" />
        </a>
      </figure>
    </div>
    <div class="box">
      <h2>Sobre Nosotros</h2>
      <p>
        Debido al aumento de empresas que han surgido en los últimos años en
        Costa Rica, teniendo en cuenta que la mayor tasa de crecimiento es de
        empresas pyme, se analiza la posibilidad de prototipar y desarrollar un
        espacio para que sus encargados o dueños de dichos negocios, puedan
        tener la confianza y libertad de postear sus servicios en el sitio web
      </p>
      <p>
        El grupo de trabajo encargado de plasmar este proyecto se ha tomado el
        tiempo de analizar todos aquellos factores que son necesarios para poder
        hacer de este sitio un modelo atractivo, funcional, intuitivo, original,
        actualizado, relevante, entre otros aspectos
      </p>
    </div>
    <div class="box">
      <h2>Redes Sociales</h2>
      <div class="social-net">
        <a href="#" class="fa fa-facebook"></a>
        <a href="#" class="fa fa-instagram"></a>
        <a href="#" class="fa fa-twitter"></a>
        <a href="#" class="fa fa-whatsapp"></a>
      </div>
    </div>
  </div>
  <div class="group-2">
    <small>&copy; 2023 <b>M.CR</b> - All rights reserved</small>
  </div>
</footer>
