<header>
  <img class="logo" src="img/logo.jpg" alt="logo" width="200px" />
  <nav>
    <ul class="nav-items">
      <li><a href="index.php">Inicio</a></li>
      <li><a href="RegistroPYMe.php">Publicar sitio</a></li>
      <li><a href="Comentar.php">Comentarios</a></li>
      <li><a href="#footer-aboutus">Sobre Nosotros</a></li>
    </ul>
  </nav>
  <a class="cta" href="#contact-a"><button>Contacto</button></a>
</header>
