<nav class="navbar" style="background-color: #e3f2fd">
  <div class="container">
    <a class="navbar-item" href="signup.php"> Registrarse </a>
    <a class="navbar-item" href="login.php"> Iniciar Sesión </a>

    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8"
      crossorigin="anonymous"
    ></script>
    <style>
      .nav_per {
        color: #130ce6;
      }
      .nav_per:hover {
        color: black;
      }
    </style>
  </div>
</nav>
