<nav class="navbar navbar-info bg-info">
  <div class="container">
    <a class="navbar-brand" href="#">
      <img
        src="imagenes/logos/perfil-del-usuario.png"
        width="50"
        height="50"
        class="d-inline-block align-top"
        alt=""
      />
      Página Principal
    </a>
    <div class="d-flex">
      <a href="https://www.facebook.com/" class="text-light me-3"
        ><i class="fab fa-facebook fa-2x"></i
      ></a>
      <br />
    </div>
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8"
      crossorigin="anonymous"
    ></script>
  </div>
</nav>
