<div class="div_pi text-center">
  <strong>Ubicados: </strong>En el aula....donde mas.<br />
  <strong>eMail: </strong>
  <a href="mailto:estudiantes@est.utn.ac.cr ?subject=Solicito información"
    >estudiantes@est.utn.ac.cr</a
  ><br />
  <strong>Teléfono: </strong>No hay
</div>
<div class="div_pc">
  Laboratorio 3 Tecnologías y sistemas Web 2<br />
  <script
    src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8"
    crossorigin="anonymous"
  ></script>
</div>
